/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;
import java.awt.event.KeyEvent;
import java.awt.Component;
import processing.core.PApplet;
import processing.core.PImage;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void simpleTest() {
        PApplet.runSketch(new String[]{"Test Constructor/draw"}, new App()); //Test App
        App classUnderTest = new App();
        assertNotNull(classUnderTest);

    }
}
