/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BerryTest {
    @Test 

    public void constructorTest() {
        Game testGame = new Game(null, "testMap.txt");
        assertNotNull(new Berry(0,0,testGame));    
    }
    @Test
    public void collectTest(){
        Game testGame = new Game(null, "testMap.txt");
        Berry test = new Berry(5,5,testGame);
        assertFalse(test.collected);//test before collect fruit
        test.collect();
        assertTrue(test.collected);//test after collect fruit

    }
    @Test
    public void resetTest(){
        Game testGame = new Game(null, "testMap.txt");
        Berry test = new Berry(5,5,testGame);
        assertFalse(test.collected);//test before collect fruit
        test.collect();
        assertTrue(test.collected); //test after collect fruit
        test.reset();
        assertFalse(test.collected); //test after reset collect fruit

    }
    @Test
    public void getCollectedTest(){
        Game testGame = new Game(null, "testMap.txt");
        Berry test = new Berry(5,5,testGame);
        assertFalse(test.isCollected());
        test.collect();
        assertTrue(test.isCollected());

    }
}
