/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FruitTest {

    @Test 
    public void constructorTest() {
    Game testGame = new Game(null, "testMap.txt");
        assertNotNull(new Fruit(0,0,testGame));    
    }
    @Test
    public void collectTest(){
    Game testGame = new Game(null, "testMap.txt");        
        Fruit test = new Fruit(5,5,testGame);
        assertFalse(test.collected); //test before collect fruit
        test.collect();
        assertTrue(test.collected);  //test after colellct

    }
    @Test
    public void resetTest(){
    Game testGame = new Game(null, "testMap.txt");
        Fruit test = new Fruit(5,5,testGame);
        assertFalse(test.collected); //test before collect fruit
        test.collect();
        assertTrue(test.collected); //test after colellct
        test.reset();
        assertFalse(test.collected); //test after reset 
    }
    @Test
    public void getCollectedTest(){
    Game testGame = new Game(null, "testMap.txt");
        Fruit test = new Fruit(5,5,testGame);
        assertFalse(test.isCollected());
        test.collect();
        assertTrue(test.isCollected());

    }
}
