/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ScoreTest {

    @Test 
    public void constructorTest() {
    Game testGame = new Game(null, "testMap.txt");
        assertNotNull(new Score(testGame,false));    
    }
    @Test
    public void highScoreTest(){
    Game testGame = new Game(null, "testMap.txt");        
        Score test = new Score(testGame,false);
        testGame.highScore = 12340;
        test.tick();
        assertEquals(testGame.number4,test.scoreDisplay[1]); //test whether score sprite display correctly
        testGame.highScore = 98765;
        test.tick();

        assertEquals(testGame.number8,test.scoreDisplay[3]); //test whether score sprite display correctly


    }
    public void currentScoreTest(){
    Game testGame = new Game(null, "testMap.txt");     
        testGame.currentScore = 1234;

        Score test = new Score(testGame,true);
        test.tick();
        assertEquals(testGame.number4,test.scoreDisplay[1]); //test whether score sprite display correctly
        testGame.highScore = 98765;
        test.tick();

        assertEquals(testGame.number8,test.scoreDisplay[3]); //test whether score sprite display correctly

    }
}
